<field:scnl itemname="生产能力" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:scnl>

<field:fays itemname="方案优势" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fays>

<field:bjzc itemname="部件组成" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bjzc>



<field:cjdp itemname="常见搭配" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cjdp>
