<dl>
                   <dt><a href='[field:arcurl/]'>
                 <img src='[field:litpic/]' width='394' height='330'></a></dt>
                 <dd><div class='tit'><h3><a href='[field:arcurl/]'>[field:title/]</a></h3>
                 <div class='case-more'><a href='[field:arcurl/]' class='case-detail' rel='nofollow'>查看详情</a> <a href='#'  rel='nofollow' onclick="javascript:window.open('../../a/cpzx');" class='case-shihe'>选择适合我的产品</a></div></div> <p> 【生产能力】：[field:scnl/] </p><p> 【方案优势】：[field:fays/] </p><p> 【组成部件】：[field:bjzc/] </p> </dd></dl>
<dl><dt><a href='[field:arcurl/]'> </p> </dd></dl>