<?php
$z[0]=Array("global","",256,276);
$z[0][4]['name']="ncrx";
$z[1]=Array("global","",302,322);
$z[1][4]['name']="ncrx";
$z[2]=Array("global","",574,591);
$z[2][4]['name']="qq";
$z[3]=Array("global","",1047,1079);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channel","\r\n                                    <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                                  ",1676,1872);
$z[4][4]['typeid']="1";
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[5]=Array("channel","\r\n                                    <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                                  ",2218,2414);
$z[5][4]['typeid']="9";
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";
$z[6]=Array("channel","\r\n                                    <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                                  ",2719,2916);
$z[6][4]['typeid']="13";
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[7]=Array("channel","\r\n                                    <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                                  ",3402,3598);
$z[7][4]['typeid']="5";
$z[7][4]['type']="son";
$z[7][4]['noself']="yes";
$z[8]=Array("channel","\r\n                                    <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                                  ",3908,4105);
$z[8][4]['typeid']="15";
$z[8][4]['type']="son";
$z[8][4]['noself']="yes";

?>