<?php
$z[0]=Array("global","",282,302);
$z[0][4]['name']="ncrx";
$z[1]=Array("global","",973,1005);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",1523,1701);
$z[2][4]['typeid']="1";
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",1921,2099);
$z[3][4]['typeid']="9";
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",2319,2498);
$z[4][4]['typeid']="13";
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[5]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",2851,3029);
$z[5][4]['typeid']="5";
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";
$z[6]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",3249,3428);
$z[6][4]['typeid']="15";
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";

?>