<?php
$z[0]=Array("global","",962,994);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",1504,1682);
$z[1][4]['typeid']="1";
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",1902,2080);
$z[2][4]['typeid']="9";
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",2300,2479);
$z[3][4]['typeid']="13";
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",2832,3010);
$z[4][4]['typeid']="5";
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[5]=Array("channel","\r\n                          <dt><a href='[field:typelink/]'>[field:typename/]</a></dt>\r\n                          ",3230,3409);
$z[5][4]['typeid']="15";
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";

?>