<?php
$z[0]=Array("field","",256,279);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",323,353);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",390,417);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",703,735);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",815,847);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",925,957);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1066,1098);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1183,1215);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1278,1310);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1382,1417);
$z[9][4]['filename']="head.htm";
$z[10]=Array("global","",1466,1498);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("channel","\r\n            <li id='leftMenu_101001'><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",1692,1852);
$z[11][4]['type']="son";
$z[11][4]['noself']="yes";
$z[12]=Array("field","",1883,1912);
$z[12][4]['name']="position";
$z[13]=Array("list","\r\n             <li><div class='img-holder'><a href='[field:arcurl/]'  target='_blank'><img src='[field:litpic/]' alt='[field:title/]' width='216' height='159' border='0' /></a></div><a href='[field:arcurl/]'>[field:title/]</a></li>\r\n\r\n\r\n            ",2007,2310);
$z[13][4]['pagesize']="30";
$z[13][4]['titlelen']="40";
$z[14]=Array("pagelist","",2533,2611);
$z[14][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[14][4]['listsize']="5";
$z[15]=Array("include","",2672,2707);
$z[15][4]['filename']="foot.htm";

?>